In [1]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [2]:
x,y=load_diabetes(return_X_y=True)

In [3]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [4]:
slr=LinearRegression()

In [5]:
slr.fit(x_train,y_train)

LinearRegression()

In [6]:
slr.intercept_

154.68310174699496

In [7]:
slr.coef_

array([ -39.47447864, -269.81263523,  512.87734364,  360.81466829,
       -691.02471002,  341.18357432,   78.37956394,  242.74269859,
        652.40611925,  111.59530529])

In [51]:
y_pred=slr.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.48660225683641845

# Now i will make my own class from scratch for multiple column using stochastic Gradient descent

In [45]:
class StochasticGradientDescent:
    def __init__ (self, learning_rate=0.1, epochs=100):
        self.lr=learning_rate
        self.epochs=epochs
        self.intercept_=None
        self.coef_=None

    def fit(self,x_train,y_train):
        self.intercept_=0
        self.coef_=np.ones(x_train.shape[1])
        for i in range (self.epochs):
            #another loop which will run according to the x_train rows size
            for j in range(x_train.shape[0]):
                idx=np.random.randint(0,x_train.shape[0])
                
                # this is for intercept_
                y_hat=np.dot(x_train[idx],self.coef_)+self.intercept_
                intercept_dirr=-2*(y_train[idx]-y_hat)
                self.intercept_=self.intercept_-(self.lr*intercept_dirr)
                
                #now for the coef_
                coef_dirr=-2*np.dot((y_train[idx]-y_hat),x_train[idx])
                self.coef_=self.coef_-(self.lr*coef_dirr)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [46]:
sgd=StochasticGradientDescent(0.01,1000)

In [47]:
sgd.fit(x_train,y_train)

In [48]:
sgd.intercept_

159.90688999656575

In [49]:
sgd.coef_

array([ -46.81019777, -277.78057383,  517.80129522,  366.70066589,
       -132.19092982, -116.15534482, -168.27888692,  169.19853582,
        452.74163389,  114.67557938])

In [50]:
y_pred=sgd.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4508340481336396

# now we will use the inbuilt class of sklearn by name SGDRegressor

In [32]:
from sklearn.linear_model import SGDRegressor

In [34]:
sgdr=SGDRegressor(max_iter=100, learning_rate='constant' ,eta0=0.1)

In [35]:
sgdr.fit(x_train,y_train)

SGDRegressor(eta0=0.1, learning_rate='constant', max_iter=100)

In [36]:
sgdr.intercept_

array([154.1308694])

In [37]:
sgdr.coef_

array([ -21.07798   , -211.04944312,  475.8048269 ,  316.3658191 ,
        -51.91527311, -105.95530764, -208.08350722,  139.29397895,
        384.63969668,  146.10527283])

In [43]:
y_pred=sgdr.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4858616773072676